// Automatically generated by MockGen. DO NOT EDIT!
// Source: UUIDGeneratorService.go

package service_test

import (
	gomock "github.com/golang/mock/gomock"
	system "github.com/micro-business/Micro-Business-Core/system"
)

// Mock of UUIDGeneratorService interface
type MockUUIDGeneratorService struct {
	ctrl     *gomock.Controller
	recorder *_MockUUIDGeneratorServiceRecorder
}

// Recorder for MockUUIDGeneratorService (not exported)
type _MockUUIDGeneratorServiceRecorder struct {
	mock *MockUUIDGeneratorService
}

func NewMockUUIDGeneratorService(ctrl *gomock.Controller) *MockUUIDGeneratorService {
	mock := &MockUUIDGeneratorService{ctrl: ctrl}
	mock.recorder = &_MockUUIDGeneratorServiceRecorder{mock}
	return mock
}

func (_m *MockUUIDGeneratorService) EXPECT() *_MockUUIDGeneratorServiceRecorder {
	return _m.recorder
}

func (_m *MockUUIDGeneratorService) GenerateRandomUUID() (system.UUID, error) {
	ret := _m.ctrl.Call(_m, "GenerateRandomUUID")
	ret0, _ := ret[0].(system.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockUUIDGeneratorServiceRecorder) GenerateRandomUUID() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "GenerateRandomUUID")
}
